[<TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\runner.py:341>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\runner.py:242>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_hooks.py:513>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_manager.py:120>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_callers.py:182>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_result.py:100>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_callers.py:167>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\threadexception.py:92>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\threadexception.py:68>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_callers.py:167>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\unraisableexception.py:95>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\unraisableexception.py:70>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_callers.py:167>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\logging.py:846>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\logging.py:829>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_callers.py:167>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\capture.py:898>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_callers.py:167>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\skipping.py:257>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_callers.py:103>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\runner.py:174>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\python.py:1627>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_hooks.py:513>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_manager.py:120>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_callers.py:139>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\pluggy\_callers.py:103>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\_pytest\python.py:159>, <TracebackEntry C:\Users\sy_li\bgtest\testcase\test_dynamic_data_source_switcher.py:168>, <TracebackEntry C:\Users\sy_li\bgtest\utils\http_utils.py:335>, <TracebackEntry C:\Users\sy_li\bgtest\utils\http_utils.py:187>, <TracebackEntry C:\Users\sy_li\bgtest\utils\http_utils.py:129>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\requests\sessions.py:589>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\requests\sessions.py:703>, <TracebackEntry C:\Users\sy_li\bgtest\.venv\lib\site-packages\requests\adapters.py:700>]