INFO     project_logger:log.py:46 开始测试: TestChatGatewayAdvanced.test_chat_gateway_data_validation
INFO     project_logger:log.py:46 请求地址: https://api.example.com/chat
INFO     project_logger:log.py:46 请求参数: {'message': ''}
INFO     api_monitor_logger:log.py:57 HTTP请求开始: {"timestamp": 1754200683.6073706, "method": "POST", "url": "https://api.example.com/chat", "params": {}, "json_data": {"message": ""}, "headers": {}}
ERROR    utils.http_utils:http_utils.py:147 请求失败: HTTPSConnectionPool(host='api.example.com', port=443): Max retries exceeded with url: /chat (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000012610A3FB10>: Failed to resolve 'api.example.com' ([Errno 11001] getaddrinfo failed)"))
ERROR    api_monitor_logger:log.py:61 HTTP请求失败: {"timestamp": 1754200683.616926, "method": "POST", "url": "https://api.example.com/chat", "status_code": null, "execution_time_ms": 9.55, "response_size": 0, "status": "error", "error": "HTTPSConnectionPool(host='api.example.com', port=443): Max retries exceeded with url: /chat (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x0000012610A3FB10>: Failed to resolve 'api.example.com' ([Errno 11001] getaddrinfo failed)\"))"}
INFO     project_logger:log.py:46 测试完成: TestChatGatewayAdvanced.test_chat_gateway_data_validation, 耗时: 0.66秒