INFO     project_logger:log.py:46 开始测试: TestDynamicDataSource.test_data_from_db_url_format
ERROR    project_logger:log.py:49 MySQL连接失败: (2003, "Can't connect to MySQL server on '8.133.246.113' (timed out)")
INFO     project_logger:log.py:46 使用db://格式从数据库加载了 0 条测试数据
INFO     project_logger:log.py:46 慢速测试警告: TestDynamicDataSource.test_data_from_db_url_format 耗时 10.01秒
INFO     project_logger:log.py:46 测试完成: TestDynamicDataSource.test_data_from_db_url_format, 耗时: 10.02秒