{"name": "test_chat_gateway_file", "status": "skipped", "statusDetails": {"message": "Skipped: 聊天网关测试执行失败: HTTPConnectionPool(host='localhost', port=8688): Max retries exceeded with url: /api/chatGatWay-internal (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000232491D9BF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))", "trace": "('E:\\\\bgtest\\\\testcase\\\\test_data_driven_example.py', 233, \"Skipped: 聊天网关测试执行失败: HTTPConnectionPool(host='localhost', port=8688): Max retries exceeded with url: /api/chatGatWay-internal (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000232491D9BF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))\")"}, "description": "测试聊天网关文件", "steps": [{"name": "测试设置: Unknown.test_chat_gateway_file", "status": "passed", "start": 1754131838203, "stop": 1754131838203}, {"name": "测试清理: Unknown.test_chat_gateway_file", "status": "passed", "start": 1754131842277, "stop": 1754131842278}], "attachments": [{"name": "log", "source": "d9c6e105-0877-414c-a488-5d833f744882-attachment.txt", "type": "text/plain"}], "start": 1754131838204, "stop": 1754131842273, "uuid": "3440fd3c-8044-4ddd-86dd-81b2c3490ff4", "historyId": "00486baf1d55dd91961dbada93ad7939", "testCaseId": "00486baf1d55dd91961dbada93ad7939", "fullName": "testcase.test_data_driven_example#test_chat_gateway_file", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_data_driven_example"}, {"name": "host", "value": "Ly0217"}, {"name": "thread", "value": "165576-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_data_driven_example"}], "titlePath": ["testcase", "test_data_driven_example.py"]}