{"name": "test_yaml_data_driven", "status": "skipped", "statusDetails": {"message": "Skipped: 测试用例执行失败: HTTPConnectionPool(host='localhost', port=8688): Max retries exceeded with url: /api/chatGatWay-internal (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014DF37A5480>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))", "trace": "('E:\\\\bgtest\\\\testcase\\\\test_data_driven_example.py', 131, \"Skipped: 测试用例执行失败: HTTPConnectionPool(host='localhost', port=8688): Max retries exceeded with url: /api/chatGatWay-internal (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014DF37A5480>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))\")"}, "description": "测试YAML数据驱动", "steps": [{"name": "测试设置: TestDataDrivenExample.test_yaml_data_driven", "status": "passed", "start": 1754139890832, "stop": 1754139890833}, {"name": "测试清理: TestDataDrivenExample.test_yaml_data_driven", "status": "passed", "start": 1754139894911, "stop": 1754139894912}], "attachments": [{"name": "log", "source": "322cc1fe-9c67-4d97-befc-e55f9436f51c-attachment.txt", "type": "text/plain"}], "start": 1754139890833, "stop": 1754139894907, "uuid": "4b2493af-5193-4d41-8c7b-d47aafed3e3f", "historyId": "d436cdda0338cc19759fb624f79aa606", "testCaseId": "d436cdda0338cc19759fb624f79aa606", "fullName": "testcase.test_data_driven_example.TestDataDrivenExample#test_yaml_data_driven", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_data_driven_example"}, {"name": "subSuite", "value": "TestDataDrivenExample"}, {"name": "host", "value": "Ly0217"}, {"name": "thread", "value": "190720-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_data_driven_example"}], "titlePath": ["testcase", "test_data_driven_example.py", "TestDataDrivenExample"]}