{"name": "test_chat_gateway_error_handling", "status": "passed", "description": "测试聊天网关错误处理", "steps": [{"name": "测试设置: TestChatGatewayAdvanced.test_chat_gateway_error_handling", "status": "passed", "start": 1754139848966, "stop": 1754139848967}, {"name": "测试用例: 聊天网关错误处理", "status": "passed", "steps": [{"name": "执行用例: error_001 - 测试无效URL", "status": "broken", "statusDetails": {"message": "Exception: 请求失败: Expecting value: line 1 column 1 (char 0)\n", "trace": "  File \"E:\\bgtest\\common\\test_utils.py\", line 274, in execute_test_case\n    response = self.execute_http_request(\n        url=case_data['url'],\n    ...<3 lines>...\n        use_allure=use_allure\n    )\n  File \"E:\\bgtest\\common\\test_utils.py\", line 133, in execute_http_request\n    raise Exception(error_msg)\n"}, "steps": [{"name": "准备请求参数", "status": "passed", "attachments": [{"name": "请求参数", "source": "123dca69-7b35-4470-8349-d78a26f62a3d-attachment.json", "type": "application/json"}], "start": 1754139848969, "stop": 1754139848972}, {"name": "发送POST请求到 https://invalid-url.com/chat", "status": "broken", "statusDetails": {"message": "Exception: 请求失败: Expecting value: line 1 column 1 (char 0)\n", "trace": "  File \"E:\\bgtest\\common\\test_utils.py\", line 133, in execute_http_request\n    raise Exception(error_msg)\n"}, "steps": [{"name": "HTTP请求: POST https://invalid-url.com/chat", "status": "broken", "statusDetails": {"message": "requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n", "trace": "  File \"E:\\bgtest\\utils\\allure_utils.py\", line 288, in http_request_with_allure\n    response = http_utils.request(method, url, **kwargs)\n  File \"E:\\bgtest\\utils\\http_utils.py\", line 293, in request\n    return response.json() if response.content else None\n           ~~~~~~~~~~~~~^^\n  File \"C:\\Python313\\Lib\\site-packages\\requests\\models.py\", line 980, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n"}, "attachments": [{"name": "Request Details", "source": "2a2358be-14f4-4f98-8250-3d87f171465f-attachment.json", "type": "application/json"}, {"name": "HTTP请求异常: POST https://invalid-url.com/chat", "source": "b0a9b31a-ad70-46aa-83d5-66c52bbfa2ac-attachment.json", "type": "application/json"}], "start": 1754139848972, "stop": 1754139850327}], "attachments": [{"name": "错误信息", "source": "4aa18304-461c-41db-b29e-a91052a698cd-attachment.txt", "type": "text/plain"}], "start": 1754139848972, "stop": 1754139850328}], "attachments": [{"name": "测试用例: error_001", "source": "128e0c36-8f55-4d28-8123-90f5fad28586-attachment.json", "type": "application/json"}], "start": 1754139848968, "stop": 1754139850329}, {"name": "执行用例: error_002 - 测试无效参数", "status": "broken", "statusDetails": {"message": "Exception: 请求失败: HTTPSConnectionPool(host='api.example.com', port=443): Max retries exceeded with url: /chat (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x0000014DF3340550>: Failed to resolve 'api.example.com' ([Errno 11001] getaddrinfo failed)\"))\n", "trace": "  File \"E:\\bgtest\\common\\test_utils.py\", line 274, in execute_test_case\n    response = self.execute_http_request(\n        url=case_data['url'],\n    ...<3 lines>...\n        use_allure=use_allure\n    )\n  File \"E:\\bgtest\\common\\test_utils.py\", line 133, in execute_http_request\n    raise Exception(error_msg)\n"}, "steps": [{"name": "准备请求参数", "status": "passed", "attachments": [{"name": "请求参数", "source": "9a7fd992-0533-43cc-bb6f-c74b0982bc4b-attachment.json", "type": "application/json"}], "start": 1754139850332, "stop": 1754139850333}, {"name": "发送POST请求到 https://api.example.com/chat", "status": "broken", "statusDetails": {"message": "Exception: 请求失败: HTTPSConnectionPool(host='api.example.com', port=443): Max retries exceeded with url: /chat (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x0000014DF3340550>: Failed to resolve 'api.example.com' ([Errno 11001] getaddrinfo failed)\"))\n", "trace": "  File \"E:\\bgtest\\common\\test_utils.py\", line 133, in execute_http_request\n    raise Exception(error_msg)\n"}, "steps": [{"name": "HTTP请求: POST https://api.example.com/chat", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.example.com', port=443): Max retries exceeded with url: /chat (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x0000014DF3340550>: Failed to resolve 'api.example.com' ([Errno 11001] getaddrinfo failed)\"))\n", "trace": "  File \"E:\\bgtest\\utils\\allure_utils.py\", line 288, in http_request_with_allure\n    response = http_utils.request(method, url, **kwargs)\n  File \"E:\\bgtest\\utils\\http_utils.py\", line 286, in request\n    response = self._make_request(method, url, **kwargs)\n  File \"E:\\bgtest\\utils\\http_utils.py\", line 129, in _make_request\n    response = self.session.request(\n        method=method,\n    ...<3 lines>...\n        **kwargs\n    )\n  File \"C:\\Python313\\Lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Python313\\Lib\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Python313\\Lib\\site-packages\\requests\\adapters.py\", line 700, in send\n    raise ConnectionError(e, request=request)\n"}, "attachments": [{"name": "Request Details", "source": "9400e0ff-9069-4ad6-8ce3-238ca6bb7387-attachment.json", "type": "application/json"}, {"name": "HTTP请求异常: POST https://api.example.com/chat", "source": "cd35a497-68b5-4c29-82c6-16575cf51f92-attachment.json", "type": "application/json"}], "start": 1754139850333, "stop": 1754139850352}], "attachments": [{"name": "错误信息", "source": "5f974eb4-e92a-4389-bcf2-0dc8a1634ef4-attachment.txt", "type": "text/plain"}], "start": 1754139850333, "stop": 1754139850355}], "attachments": [{"name": "测试用例: error_002", "source": "fcf088fc-ea4c-446e-aa27-26159f77d9fe-attachment.json", "type": "application/json"}], "start": 1754139850331, "stop": 1754139850357}], "attachments": [{"name": "执行时间", "source": "8a037447-6393-4b51-99c3-514faea2145c-attachment.txt", "type": "text/plain"}], "start": 1754139848968, "stop": 1754139850360}, {"name": "测试清理: TestChatGatewayAdvanced.test_chat_gateway_error_handling", "status": "passed", "start": 1754139850361, "stop": 1754139850363}], "attachments": [{"name": "log", "source": "d02cfdb9-e8fa-4620-a3a2-8be9c3ba14a2-attachment.txt", "type": "text/plain"}], "start": 1754139848968, "stop": 1754139850360, "uuid": "72918f31-fa7b-4b6a-8926-02ce717454c7", "historyId": "b51b754f6ff9ac00098a682d0088ad3e", "testCaseId": "b51b754f6ff9ac00098a682d0088ad3e", "fullName": "testcase.test_chat_gateway_optimized.TestChatGatewayAdvanced#test_chat_gateway_error_handling", "labels": [{"name": "story", "value": "错误处理"}, {"name": "feature", "value": "聊天网关"}, {"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_chat_gateway_optimized"}, {"name": "subSuite", "value": "TestChatGatewayAdvanced"}, {"name": "host", "value": "Ly0217"}, {"name": "thread", "value": "190720-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_chat_gateway_optimized"}], "titlePath": ["testcase", "test_chat_gateway_optimized.py", "TestChatGatewayAdvanced"]}